# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wgK0hHQ2o49gF0UNTifYS6MsPc23fqPY
"""

import streamlit as st
import joblib
import numpy as np

st.set_page_config(layout="wide")
st.title("Agriculture Supply Chain Risk Prediction 🌾")
st.write("Please enter the details below to predict risk:")

model_path = 'log_reg_model.pkl'
model = joblib.load(model_path)
le_risk_path ='label_encoder_risk.pkl'
le_risk = joblib.load(le_risk_path)
expected_features = model.n_features_in_

st.info(f"Your model needed features: {expected_features}")

minmax_scaler = joblib.load('min_max_scaler.pkl')
standard_scaler = joblib.load('std_scaler.pkl')
robust_scaler = joblib.load('robust_scaler.pkl')

Spoilage_Risk_Score = st.number_input("Spoilage Risk Score", value=0.0)
Agri_Supply_Chain_Risk_Score = st.number_input("Agri Supply Chain Risk Score", value=0.0)
Post_Harvest_Loss_pct = st.number_input("Post Harvest Loss %", value=0.0)
Port_Congestion_Index = st.number_input("Port Congestion Index", value=0.0)
Price_Volatility_Index = st.number_input("Price Volatility Index", value=0.0)
Food_Safety_Risk_Index = st.number_input("Food Safety Risk Index", value=0.0)
Exchange_Rate_Index = st.number_input("Exchange Rate Index", value=0.0)
Global_Price_Index = st.number_input("Global Price Index", value=0.0)


if st.button("Predict"):
    scaled_minmax = minmax_scaler.transform([[Port_Congestion_Index]])[0]
    scaled_standard = standard_scaler.transform([[Spoilage_Risk_Score,Agri_Supply_Chain_Risk_Score,Post_Harvest_Loss_pct,Global_Price_Index]])[0]
    scaled_robust = robust_scaler.transform([[Food_Safety_Risk_Index,Exchange_Rate_Index,Price_Volatility_Index]])[0]

    features = [
       scaled_standard[0],
    #Spoilage_Risk_Score
       scaled_standard[1],
    #Agri_Supply_Chain_Risk_Score
       scaled_standard[2],
    #Post_Harvest_Loss_pct
       scaled_minmax[0],
   #Port_Congestion_Index
       scaled_robust[2],
    #Price_Volatility_Index
       scaled_robust[0],
    #Food_Safety_Risk_Index
       scaled_robust[1],
    #Exchange_Rate_Risk_Index
       scaled_standard[3]
        
    ]


    if len(features) < expected_features:
        features += [0.0] * (expected_features - len(features))
    elif len(features) > expected_features:
        features = features[:expected_features]

    features_array = np.array([features])
    prediction = model.predict(features_array)
    raw_predicted_number = prediction[0]
    st.write(f"{raw_predicted_number}")




    st.subheader("Prediction Result:")

    #if risk_label == "Moderate":
        st.warning(f"⚠️ Moderate Risk Detected!")
    
    #elif risk_label == "Low":
        st.success(f"✅ Low Risk / Safe!")
    
